// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: bsv21.proto

package bsv21

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bsv21 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Op       string `protobuf:"bytes,2,opt,name=op,proto3" json:"op,omitempty"`
	Amt      uint64 `protobuf:"varint,3,opt,name=amt,proto3" json:"amt,omitempty"`
	Dec      uint32 `protobuf:"varint,4,opt,name=dec,proto3" json:"dec,omitempty"`
	Sym      string `protobuf:"bytes,5,opt,name=sym,proto3" json:"sym,omitempty"`
	Icon     []byte `protobuf:"bytes,6,opt,name=icon,proto3" json:"icon,omitempty"`
	Contract string `protobuf:"bytes,7,opt,name=contract,proto3" json:"contract,omitempty"`
	Status   int32  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	Reason   string `protobuf:"bytes,9,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Bsv21) Reset() {
	*x = Bsv21{}
	if protoimpl.UnsafeEnabled {
		mi := &file_bsv21_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Bsv21) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bsv21) ProtoMessage() {}

func (x *Bsv21) ProtoReflect() protoreflect.Message {
	mi := &file_bsv21_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bsv21.ProtoReflect.Descriptor instead.
func (*Bsv21) Descriptor() ([]byte, []int) {
	return file_bsv21_proto_rawDescGZIP(), []int{0}
}

func (x *Bsv21) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bsv21) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

func (x *Bsv21) GetAmt() uint64 {
	if x != nil {
		return x.Amt
	}
	return 0
}

func (x *Bsv21) GetDec() uint32 {
	if x != nil {
		return x.Dec
	}
	return 0
}

func (x *Bsv21) GetSym() string {
	if x != nil {
		return x.Sym
	}
	return ""
}

func (x *Bsv21) GetIcon() []byte {
	if x != nil {
		return x.Icon
	}
	return nil
}

func (x *Bsv21) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *Bsv21) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Bsv21) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_bsv21_proto protoreflect.FileDescriptor

var file_bsv21_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x62, 0x73, 0x76, 0x32, 0x31, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x62,
	0x73, 0x76, 0x32, 0x31, 0x22, 0xbd, 0x01, 0x0a, 0x05, 0x42, 0x73, 0x76, 0x32, 0x31, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x6d, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x61, 0x6d, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x64, 0x65, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x64,
	0x65, 0x63, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x79, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x73, 0x79, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x42, 0x0b, 0x5a, 0x09, 0x6d, 0x6f, 0x64, 0x2f, 0x62, 0x73, 0x76, 0x32,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_bsv21_proto_rawDescOnce sync.Once
	file_bsv21_proto_rawDescData = file_bsv21_proto_rawDesc
)

func file_bsv21_proto_rawDescGZIP() []byte {
	file_bsv21_proto_rawDescOnce.Do(func() {
		file_bsv21_proto_rawDescData = protoimpl.X.CompressGZIP(file_bsv21_proto_rawDescData)
	})
	return file_bsv21_proto_rawDescData
}

var file_bsv21_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_bsv21_proto_goTypes = []interface{}{
	(*Bsv21)(nil), // 0: bsv21.Bsv21
}
var file_bsv21_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_bsv21_proto_init() }
func file_bsv21_proto_init() {
	if File_bsv21_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_bsv21_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Bsv21); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_bsv21_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_bsv21_proto_goTypes,
		DependencyIndexes: file_bsv21_proto_depIdxs,
		MessageInfos:      file_bsv21_proto_msgTypes,
	}.Build()
	File_bsv21_proto = out.File
	file_bsv21_proto_rawDesc = nil
	file_bsv21_proto_goTypes = nil
	file_bsv21_proto_depIdxs = nil
}
